stages:
  - build

.defaults-win: &defaults-win
  stage: build
  tags:
    - msvc
  artifacts:
    name: "${env:CI_JOB_NAME}-${env:CI_COMMIT_SHORT_SHA}"
    expire_in: 1 month
    paths:
      - output/Windows
  only: 
    - master

.defaults-linux: &defaults-linux
  stage: build
  tags:
    - linux
  artifacts:
    name: "${CI_JOB_NAME}-${CI_COMMIT_SHORT_SHA}"
    expire_in: 1 month
    paths:
      - output/Linux
  only: 
    - master

.defaults-android: &defaults-android
  stage: build
  tags:
    - android
  artifacts:
    name: "${CI_JOB_NAME}-${CI_COMMIT_SHORT_SHA}"
    expire_in: 1 month
    paths:
      - output/Android
  only: 
    - master


test-msvc:
  <<: *defaults-win
  script:
    - Set-Content -Path local.properties -Value "def.PROJECT_DIRNAME = test"
    - .\gradlew.bat build-14-all

test-linux:
  <<: *defaults-linux
  script:
    - echo def.PROJECT_DIRNAME = test > local.properties
    - chmod +x tools/cmake/bin/cmake
    - chmod +x gradlew
    - ./gradlew build-linux-all

test-android:
  <<: *defaults-android
  script:
    - echo def.PROJECT_DIRNAME = test > local.properties
    - chmod +x tools/cmake/bin/cmake
    - chmod +x tools/ninja/ninja
    - chmod +x gradlew
    - ./gradlew build-android-all